import { resolveRelative } from "../util/path"
import { QuartzPluginData } from "../plugins/vfile"
import { QuartzComponent, QuartzComponentConstructor, QuartzComponentProps } from "./types"

const css = `
.prev-next {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 1rem;
  margin: 0.75rem 0;
  font-size: 0.95em;
}
.prev-next .pn-cell {
  display: flex;
  flex-direction: column;
  gap: 0.15rem;
  min-width: 0;
}
.prev-next .pn-cell.pn-next {
  text-align: right;
  align-items: flex-end;
}
.prev-next .pn-label {
  color: var(--gray);
  font-size: 0.85em;
}
.prev-next .pn-title {
  color: var(--secondary);
  text-decoration: none;
  font-weight: 500;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  max-width: 100%;
}
.prev-next .pn-title:hover {
  text-decoration: underline;
}

.similar-pages {
  margin: 0.75rem 0 1rem;
  font-size: 0.95em;
}
.similar-pages h3 {
  font-size: 1em;
  margin: 0 0 0.4rem;
  color: var(--darkgray);
}
.similar-pages ul {
  list-style: none;
  padding: 0;
  margin: 0;
  display: flex;
  flex-direction: column;
  gap: 0.2rem;
}
.similar-pages li {
  display: flex;
  gap: 0.5rem;
  align-items: baseline;
}
.similar-pages li a.internal {
  color: var(--secondary);
  text-decoration: none;
}
.similar-pages li a.internal:hover {
  text-decoration: underline;
}
.similar-pages .shared-tags {
  color: var(--gray);
  font-size: 0.85em;
}
`

const TOP_LEVEL_SLUGS = new Set([
  "about",
  "all",
  "contact",
  "metadata",
  "tags",
  "writing/index",
])

function isIndex(slug: string | undefined): boolean {
  return !slug || slug === "index"
}

function isWritingEssay(slug: string): boolean {
  return slug.startsWith("writing/") && slug !== "writing/index"
}

function getSiblings(self: QuartzPluginData, all: QuartzPluginData[]): QuartzPluginData[] {
  const slug = self.slug
  if (!slug) return []
  if (isIndex(slug)) return []
  if (isWritingEssay(slug)) {
    return all
      .filter((f) => f.slug && isWritingEssay(f.slug))
      .slice()
      .sort((a, b) => {
        const ad = a.dates?.created?.getTime() ?? 0
        const bd = b.dates?.created?.getTime() ?? 0
        return ad - bd
      })
  }
  if (TOP_LEVEL_SLUGS.has(slug)) {
    const fixedOrder = ["about", "all", "writing/index", "metadata", "contact", "tags"]
    const inOrder: QuartzPluginData[] = []
    for (const wantSlug of fixedOrder) {
      const f = all.find((x) => x.slug === wantSlug)
      if (f) inOrder.push(f)
      else if (wantSlug === "tags") {
        // Synthetic Tags entry (auto-generated by Quartz, not in allFiles)
        inOrder.push({
          slug: "tags",
          frontmatter: { title: "Tags", tags: [] },
        } as QuartzPluginData)
      }
    }
    return inOrder
  }
  return []
}

function findPrevNext(
  self: QuartzPluginData,
  siblings: QuartzPluginData[],
): { prev: QuartzPluginData | null; next: QuartzPluginData | null } {
  const idx = siblings.findIndex((f) => f.slug === self.slug)
  if (idx < 0) return { prev: null, next: null }
  return {
    prev: idx > 0 ? siblings[idx - 1] : null,
    next: idx < siblings.length - 1 ? siblings[idx + 1] : null,
  }
}

function getSimilarPages(self: QuartzPluginData, all: QuartzPluginData[]): QuartzPluginData[] {
  const tags = (self.frontmatter?.tags as string[] | undefined) ?? []
  if (tags.length === 0) return []
  const tagSet = new Set(tags)

  const scored: { page: QuartzPluginData; shared: number }[] = []
  for (const f of all) {
    if (!f.slug) continue
    if (f.slug === self.slug) continue
    if (f.slug.startsWith("tags/")) continue
    if (f.slug === "404") continue
    const ft = (f.frontmatter?.tags as string[] | undefined) ?? []
    let shared = 0
    for (const t of ft) if (tagSet.has(t)) shared += 1
    if (shared > 0) scored.push({ page: f, shared })
  }

  scored.sort((a, b) => b.shared - a.shared)
  return scored.slice(0, 5).map((s) => s.page)
}

const PrevNext: QuartzComponent = ({ fileData, allFiles }: QuartzComponentProps) => {
  if (isIndex(fileData.slug)) return null
  const siblings = getSiblings(fileData, allFiles)
  const { prev, next } = findPrevNext(fileData, siblings)
  const similar = getSimilarPages(fileData, allFiles)

  const linkTo = (target: QuartzPluginData) =>
    resolveRelative(fileData.slug!, target.slug!)

  if (!prev && !next && similar.length === 0) return null

  return (
    <>
      {(prev || next) && (
        <nav class="prev-next" aria-label="Previous and next">
          <div class="pn-cell pn-prev">
            {prev && (
              <>
                <span class="pn-label">← Previous</span>
                <a class="pn-title" href={linkTo(prev)}>
                  {(prev.frontmatter?.title as string) ?? prev.slug}
                </a>
              </>
            )}
          </div>
          <div class="pn-cell pn-next">
            {next && (
              <>
                <span class="pn-label">Next →</span>
                <a class="pn-title" href={linkTo(next)}>
                  {(next.frontmatter?.title as string) ?? next.slug}
                </a>
              </>
            )}
          </div>
        </nav>
      )}
      {similar.length > 0 && (
        <div class="similar-pages">
          <h3>Related</h3>
          <ul>
            {similar.map((p) => {
              const ftags = ((p.frontmatter?.tags as string[] | undefined) ?? [])
                .filter((t) =>
                  ((fileData.frontmatter?.tags as string[] | undefined) ?? []).includes(t),
                )
                .join(", ")
              return (
                <li>
                  <a class="internal" href={linkTo(p)}>
                    {(p.frontmatter?.title as string) ?? p.slug}
                  </a>
                  {ftags && <span class="shared-tags">— shared: {ftags}</span>}
                </li>
              )
            })}
          </ul>
        </div>
      )}
    </>
  )
}

PrevNext.css = css

export default (() => PrevNext) satisfies QuartzComponentConstructor
